services:
  rc_server:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        repo: ../
      args:
        PUBLIC_JWT_KEY:
        SSL_CERTIFICATE:
        SSL_PRIVATE_KEY:
        ASSETS_DIR: /assets/
    ports:
      - "25568:25568/udp"
    volumes:
        - server_data:/server

volumes:
  server_data: