services:
  api:
    build:
      context: .
      args:
        JWT_PRIVATE_KEY:
        JWT_PUBLIC_KEY:
    ports:
      - "3001:3001"
    healthcheck:
      test: 'wget -qO- http://localhost:3001 || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5